// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 12-2-1 ÏÂÎç4:09    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
//using Common.Utility.Basis;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;

namespace COM.MeshStudio.Lib.Rule
{	
	public class BasicRulePart {
		private SVOClause svoClause;
		private RuleSVOExplainer svoExplainer;
	
		public BasicRulePart() {
			svoClause = new SVOClause();
			svoExplainer = new RuleSVOExplainer();
		}
	
		public BasicRulePart(RuleSVOExplainer svoExplainer_0) {
			svoClause = new SVOClause();
			this.svoExplainer = svoExplainer_0;
		}
	
		public BasicRulePart(SVOClause svoClause_0, RuleSVOExplainer svoExplainer_1) {
			this.svoClause = svoClause_0;
			this.svoExplainer = svoExplainer_1;
		}
	
		public Object ExplainMe(Object parameterObjectSub,
				Object[] methodParametersSub, Object parameterObjectVer,
				Object[] methodParametersVer, Object parameterObjectObj,
				Object[] methodParametersObj) {
			svoExplainer.ExplainRuleSVO(svoClause, parameterObjectSub,
					methodParametersSub, parameterObjectVer, methodParametersVer,
					parameterObjectObj, methodParametersObj);
			return svoExplainer.GetRuleResultObj();
		}
	
		public void SaveSVOClause2File(String xmlFile) {
			XMLOperatorRule xmlOpr = new XMLOperatorRule();
			List<SVOClause> svoClauseList = new List<SVOClause>();
			ILOG.J2CsMapping.Collections.Collections.Add(svoClauseList,svoClause);
			xmlOpr.AppendXML(xmlFile, svoClauseList);
		}
	
		public SVOClause GetSvoClause() {
			return svoClause;
		}
	
		public void SetSvoClause(SVOClause svoClause_0) {
			this.svoClause = svoClause_0;
		}
	
		public RuleSVOExplainer GetSvoExplainer() {
			return svoExplainer;
		}
	
		public void SetSvoExplainer(RuleSVOExplainer svoExplainer_0) {
			this.svoExplainer = svoExplainer_0;
		}
	}
}
