// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 12-2-1 ÏÂÎç4:09    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
	
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;

namespace COM.MeshStudio.Lib.Rule
{
	public class RuleConstraint : BasicRulePart {
		private bool constraintResult;
	
		public RuleConstraint() : base() {
			this.constraintResult = false;
		}
	
		public RuleConstraint(SVOClause svoClause, RuleSVOExplainer svoExplainer) {
			this.constraintResult = false;
			this.SetSvoClause(svoClause);
			this.SetSvoExplainer(svoExplainer);
		}
	
		public bool ExplainConstraint(Object parameterObjectSub,
				Object[] methodParametersSub, Object parameterObjectVer,
				Object[] methodParametersVer, Object parameterObjectObj,
				Object[] methodParametersObj) {
			try {
				constraintResult = (bool)(((Boolean)base.ExplainMe(parameterObjectSub,methodParametersSub,parameterObjectVer,methodParametersVer,parameterObjectObj,methodParametersObj)));
			} catch (Exception e) {
				// TODO Auto-generated catch block
				Console.Error.WriteLine(e.StackTrace);
			}
			return constraintResult;
		}
	
		public bool IsConstraintResult() {
			return constraintResult;
		}
	
		public void SetConstraintResult(bool constraintResult_0) {
			this.constraintResult = constraintResult_0;
		}
	}
}
