// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 12-2-1 ÏÂÎç4:09    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;

namespace COM.MeshStudio.Lib.Rule
{
	public class RuleItem {
		private String ruleName;
		private RuleCondition ruleCondition;
		private RuleConstraint ruleConstraint;
		private RuleConsequence ruleConsequence;
	
		public RuleItem(String ruleName_0) {
			this.ruleName = ruleName_0;
			ruleCondition = new RuleCondition();
			ruleConstraint = new RuleConstraint();
			ruleConsequence = new RuleConsequence();
		}
	
		public Object GetRuleRunningResult(
				List<List<Object>> parameterObjectLists,
				List<List<Object[]>> methodParametersLists) {
			Object result = null;
			List<Object> parameterObjectListCondition = parameterObjectLists[0];
			List<Object[]> methodParameterListCondition = methodParametersLists[0];
			List<Object> parameterObjectListConstraint = parameterObjectLists[2];
			List<Object[]> methodParameterListConstraint = methodParametersLists[2];
			List<Object> parameterObjectListConsequence = parameterObjectLists[1];
			List<Object[]> methodParameterListConsequence = methodParametersLists[1];
			bool conditionResult = ruleCondition.ExplainCondition(
					parameterObjectListCondition[0],
					methodParameterListCondition[0],
					parameterObjectListCondition[1],
					methodParameterListCondition[1],
					parameterObjectListCondition[2],
					methodParameterListCondition[2]);
			bool constraintResult = ruleConstraint.ExplainConstraint(
					parameterObjectListConstraint[0],
					methodParameterListConstraint[0],
					parameterObjectListConstraint[1],
					methodParameterListConstraint[1],
					parameterObjectListConstraint[2],
					methodParameterListConstraint[2]);
			if (conditionResult & constraintResult) {
				result = ruleConsequence.ExplainConsequence(
						parameterObjectListConsequence[0],
						methodParameterListConsequence[0],
						parameterObjectListConsequence[1],
						methodParameterListConsequence[1],
						parameterObjectListConsequence[2],
						methodParameterListConsequence[2]);
			}
			return result;
		}
	
		public RuleCondition GetRuleCondition() {
			return ruleCondition;
		}
	
		public RuleConsequence GetRuleConsequence() {
			return ruleConsequence;
		}
	
		public RuleConstraint GetRuleConstraint() {
			return ruleConstraint;
		}
	
		public void SetRuleCondition(RuleCondition ruleCondition_0) {
			this.ruleCondition = ruleCondition_0;
		}
	
		public void SetRuleConsequence(RuleConsequence ruleConsequence_0) {
			this.ruleConsequence = ruleConsequence_0;
		}
	
		public void SetRuleConstraint(RuleConstraint ruleConstraint_0) {
			this.ruleConstraint = ruleConstraint_0;
		}
	
		public String GetRuleName() {
			return ruleName;
		}
	
		public void SetRuleName(String ruleName_0) {
			this.ruleName = ruleName_0;
		}
	}
}
