// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 12-2-1 ÏÂÎç4:09    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;

namespace COM.MeshStudio.Lib.Rule
{	
	public class RuleEnum {
		public enum RuleParts {
			CONDITION, CONSTRAINT, CONSEQUENCE
		} 
	
		public enum RuleModes {
			WHOLE, EACH
		} 
	
		public enum RuleSubjects {
			VALUE, INTERN, LIST, CONSTRUCT_LIST, DATE, WEEKDAY, TIME, OBJECT, OBJECT_FIELD, OBJECT_METHOD, OBJECT_METHOD_LIST, OBJECT_FIELD_PARA, OBJECT_METHOD_PARA, OBJECT_METHOD_LIST_PARA, EXPRESSION, RULE_PART, NONE
		} 
	
		public enum RuleVerbs {
			EQUALS, NOT_EQUALS, LARGER_THAN, LESS_THAN, NOT_LARGER_THAN, NOT_LESS_THAN, NOT, AND, OR, EARLY_THAN, LATER_THAN, BETWEEN, SOMETIME_EARIER, SOMETIME_LATER, HAVING, BELONG, INSIDE, OUTSIDE, OVERLAP, APPEND, DELETE, MERGE, UNION, INTERSECTION, EXCLUDE, COUNT_ELEMENT, COUNT_OVERLAP, COUNT_MAX_SAME, COUNT, DISTINCT, DISTINCT_COUNT, EVALUATE, PRESENT, DISCOUNT, REMIT, PRESENT_MORE, PRESENT_WITHIN, EVERY, EVERY_WITHIN, PARTIAL_DISCOUNT, SET, CALL, EXPRESSION_VALUE, SELECT, SELECT_WHERE, NONE
		} 
	
		public enum RuleObjects {
			VALUE, INTERN, LIST, CONSTRUCT_LIST, DATE, WEEKDAY, TIME, HOLIDAYS, OBJECT, OBJECT_FIELD, OBJECT_METHOD, OBJECT_METHOD_LIST, OBJECT_FIELD_PARA, OBJECT_METHOD_PARA, OBJECT_METHOD_LIST_PARA, LOCK, UNLOCK, EXPRESSION, VARIABLE_LIST, RULE_PART, NONE
		} 
	
	}
}
